name: 'Setup SBT'
description: 'Does SBT Setup'
inputs:
  java-version:
    description: 'JDK Version'
    required: false
    default: 15-ea
  github-token:
    description: 'Github Token For Override'
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: "composite"
  steps:
  - id: Set up JDK
    uses: actions/setup-java@v1
    with:
      java-version: ${{ inputs.java-version }}
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0
      token: ${{ inputs.github-token }}
  - name: Cache Dependencies
    uses: actions/cache@v2
    with:
      path: |
        ~/.sbt
        ~/.ivy2/cache
        ~/.coursier/cache/v1
        ~/.cache/coursier/v1
      key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
